### ISSUE TITLE
Restarting nix-sandbox haskell session

### ISSUE THREAD

**Issue by NerdGGuy** [wedens/dotfiles#2]
Hi,

I came across your spacemacs config when trying to setup nix-sandbox, works great so far, thanks! But I have been unable to work out how to reset the session after i make changes to cabal/shell.nix. Other then restarting emacs I'm unable to get the session to recognize new package dependencies. Any ideas?

**Comment by NerdGGuy** [comment]
My bad, I think I have some configuration issue so started again. I noticed
    (when (executable-find "nix-shell")
doesn't work on my NIXOS setup so I removed it and everything seems to be working again :).

**Comment by wedens** [comment]
glad you figured it out :)
` (when (executable-find "nix-shell")` may not work for you if `PATH` in emacs is different
